### ISSUE TITLE
Code server not loading

### ISSUE THREAD

**Issue by Servando1990** [abhishekkrthakur/ml_dev_env#1]
Hello!

I've followed every step of the process and not viewing anything on the browser. 

Tried:
- host 0.0.0.0 with CPORT: 10012
- host 127.0.0.1 with CPORT: 10012

Anything I missed?

![image](https://user-images.githubusercontent.com/30570664/90615974-1b60c380-e20d-11ea-8260-481abdcf5372.png)
![image](https://user-images.githubusercontent.com/30570664/90616364-a346cd80-e20d-11ea-8e01-fd90fe5ffb05.png)

**Comment by abhishekkrthakur** [comment]
That's weird. Whats the error that you get? or the page doesnt load at all?

BTW, thanks for trying. I'm still building this :)

**Comment by abhishekkrthakur** [comment]
The page wont open automatically btw.

**Comment by Servando1990** [comment]
The page doesn't load at all :)

Yes, I'm copying and pasting the URL :)

Thanks to you. Big fan btw

**Comment by albertoburgosplaza** [comment]
Hi all,

I had the same issue. I replaced the host network mode with a published port:

```
--network=host \
```
to:
```
-p $(CPORT):$(CPORT) \
```

Nice project! I'm experimenting with docker after reading your book. Thank you.

**Comment by Servando1990** [comment]
It works!! thanks, both of you
